version: '3.1'

services:
  db:
    container_name: bch-db
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dbtest
    ports:
        - 15432:5432

  php:
    container_name: bch-php
    build:
      context: ./php
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../app/:/var/www
    ports:
      - "9000:9000"

  nginx:
    container_name: bch-nginx
    build:
      context: ./nginx
    volumes:
      - ./../app/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "82:82"


